### ISSUE TITLE
Question - Item file location

### ISSUE THREAD

**Issue by neooblaster** [marius00/iagd#72]
Hi marius,

I have a question.
Once you loaded game data, there is a file name userdata.db
Items collected from the game are in this file or they are in the transfer.xx.gs_ files ?
I try to sync data between 2 computers throught Internet, but this file is too larger to share it.

Thanks for your help !

Neoblaster

**Comment by marius00** [comment]
Questions are easier on discord, but as a one off I'll answer ;)

Items looted by IA are stored in userdata.db. The file is large because it also contains a ton of information from Grim Dawn itself. 

If you want to sync the data between two computers, go to backup, click login, and then login using your email. Then go to settings and click "using two computers".

IA will then automagically sync your items between the two computers you've logged into.

**Comment by neooblaster** [comment]
Hi Marius,

Thanks for your reply. I will try to use the functionnality throught your sync service.
Thanks again for this USEFULL tool !

Kindly Regards,
Neo
