### ISSUE TITLE
Totally offtopic (about GrimDamage)

### ISSUE THREAD

**Issue by swasher** [marius00/iagd#90]
Dear Marius!

It's only one exist tool for GD for people, which want to testing their builds, analyze gameplay for find bottleneck or choosing best gear/build. I think, many people will use it. Also this tool look have really cool! :)

If you can find some time for further developing, many people will thank you. At least adapt old for x64 version. Because there is no similar tool in the world.

We all thank you for your work!

**Comment by marius00** [comment]
Hi.

While I initially thought this tool was a great idea, it never received any widespread adoptions.
The current user count (http://ribbs.dreamcrash.org/gddamage/logs.php) is at 29, which is roughly half of its peak popularity.

There simply isn't a user base for this tool, not one large enough to justify the development effort in building and maintaining such a tool.

Initially I made it because it was sometimes hard to see what actually killed you.
